@extends('layouts.app')
@section('title', 'Articles — ProjectNEMO')
@section('extra-styles')
.filter-bar { display:flex;gap:0.8rem;justify-content:center;margin-bottom:3rem;flex-wrap:wrap; }
.filter-btn { padding:0.5rem 1.3rem;border-radius:50px;border:2px solid rgba(26,60,42,0.15);background:transparent;color:var(--text-muted);font-weight:600;font-size:0.85rem;cursor:pointer;transition:all 0.3s;font-family:'Source Sans 3',sans-serif; }
.filter-btn:hover,.filter-btn.active { background:var(--forest);color:white;border-color:var(--forest); }
@endsection
@section('content')
<div class="page-hero"><p class="page-hero-label">Articles & Research</p><h1>Stories That <em>Matter</em></h1><p>In-depth reporting on the issues shaping our natural world.</p></div>
<section class="section"><div class="container"><div class="filter-bar"><button class="filter-btn active">All</button><button class="filter-btn">Ocean</button><button class="filter-btn">Wildlife</button><button class="filter-btn">Climate</button><button class="filter-btn">Vet Medicine</button><button class="filter-btn">Sustainability</button></div><div class="grid-3"><a href="#" class="card"><div class="card-img ocean"><span>&#127754;</span><span class="card-category">Ocean</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>The Silent Crisis Beneath Our Waves</h3><p>Exploring the devastating impact of microplastics on marine ecosystems and what we can do to turn the tide.</p><span class="card-link">Read More &rarr;</span></div></a><a href="#" class="card"><div class="card-img wildlife"><span>&#129421;</span><span class="card-category">Wildlife</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>Vanishing Habitats: A Global Emergency</h3><p>How deforestation and urban sprawl are pushing species to the brink of extinction.</p><span class="card-link">Read More &rarr;</span></div></a><a href="#" class="card"><div class="card-img climate"><span>&#127777;&#65039;</span><span class="card-category">Climate</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>Sustainability Starts at Home</h3><p>Practical steps every individual can take to reduce their environmental footprint.</p><span class="card-link">Read More &rarr;</span></div></a><a href="#" class="card"><div class="card-img vet"><span>&#128062;</span><span class="card-category">Vet Medicine</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>Wildlife Rehabilitation: Healing the Wild</h3><p>Inside the clinics and sanctuaries working to save injured and orphaned animals.</p><span class="card-link">Read More &rarr;</span></div></a><a href="#" class="card"><div class="card-img sustain"><span>&#127793;</span><span class="card-category">Sustainability</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>Regenerative Agriculture: Farming for the Future</h3><p>How innovative farming practices are restoring soil health and fighting climate change.</p><span class="card-link">Read More &rarr;</span></div></a><a href="#" class="card"><div class="card-img forest"><span>&#127795;</span><span class="card-category">Conservation</span></div><div class="card-body"><p class="card-date">Coming Soon</p><h3>Reforesting the Planet One Tree at a Time</h3><p>Global tree-planting initiatives and their measurable impact on biodiversity.</p><span class="card-link">Read More &rarr;</span></div></a></div></div></section>
@endsection
